.TH bob 1 bob\-1.0.0
.SH NAME
bob \- Binary Only Packager Manager
.SH SYNOPSIS
.B bob
.RB [ install|i|add ]
.RB [ uninstall|d|del ]
.RB [ update|u ]
.RB [ search|s ]
.RB [ list|s ]

.SH DESCRIPTION
bob is a Binary Only package manager that is for managing my publicly published softwares.
.PP
.SH USAGE
.
.nf
 (install|i|add) <package>	Install a package
 (uninstall|d|del) <package>	Uninstall a package
 (update|u) <package>		Update a package
 (search|s) <package>		Search for a package
 (list|l) [all]			List all packages installed/available

.SH AUTHOR
Made by Night Kaly
.B <night@night0721.xyz>
